Add sorting by business server order
Flexberry/NewPlatform.Flexberry.ORM pull request #166
Opened 2021-02-17 07:41 UTC by AlexBurmatov

2021-02-17 09:42 UTC, NicholasNoise requested changes

2021-02-17 09:42 UTC, NicholasNoise commented on NewPlatform.Flexberry.ORM.Tests/ICSSoft.STORMNET.Business/BusinessServerDefaultOrderTests.cs
> +        public void GetBusinessServerOrderForClass0()
Сделай тест более независимым от остальных классов - сложно понять, что из-за `Order = 1` меняется порядок: сначала БС, а потом интерфейс.

2021-02-18 07:32 UTC, NicholasNoise approved these changes

2021-02-19 06:44 UTC, NicholasNoise commented on NewPlatform.Flexberry.ORM.Tests/ICSSoft.STORMNET.Business/BusinessServerCustomOrderTests.cs
> +
Коммент.

2021-02-19 13:57 UTC, bratchikov requested changes

2021-02-19 13:57 UTC, bratchikov commented on NewPlatform.Flexberry.ORM.Tests/ICSSoft.STORMNET.Business/BusinessServerCustomOrderTests.cs
> +            var bss = BusinessServerProvider.GetBusinessServer(type, DataServiceObjectEvents.OnInsertToStorage, null);
var используем только в тех местах, где по правой части можно понять какой тип у переменной будет. В данном случае тип нельзя определить.

2021-02-19 13:57 UTC, bratchikov commented on NewPlatform.Flexberry.ORM.Tests/ICSSoft.STORMNET.Business/BusinessServerCustomOrderTests.cs
> +        public void GetBusinessServerOrderForClass1()
Добавьте XML-комментарии к публичным методам и вложенным классам.

2021-02-20 13:35 UTC, AlexBurmatov commented on NewPlatform.Flexberry.ORM.Tests/ICSSoft.STORMNET.Business/BusinessServerCustomOrderTests.cs
> +        public void GetBusinessServerOrderForClass1()
Какие можно добавить комментарии к классам-пустышкам?

2021-03-10 11:00 UTC, bratchikov approved these changes

2021-03-10 11:00 UTC, merged