Fix catching and rethrowing a query exception
Flexberry/NewPlatform.Flexberry.ORM pull request #222
Opened 2022-04-22 15:30 UTC by NicholasNoise

2022-04-25 08:51 UTC, mao29 approved these changes

2022-04-25 12:19 UTC, mao29 requested changes

2022-04-25 12:19 UTC, mao29 commented on NewPlatform.Flexberry.ORM.IntegratedTests/ICSSoft.STORMNET.Business/SQLDataServiceTest.Exceptions.cs
> +                Assert.Throws<ExecutingQueryException>(() => dataService.UpdateObject(bear));
Я правильно понимаю что суть исправления чтобы нормальное сообщение выдавалось, именно про скрипт, который упал? Предлагаю в тесте проверить еще и текст сообщения. Не знаю правда какой он для Oracle...

2022-06-03 08:41 UTC, bratchikov reviewed
Please add descriptions of changes into CHANGELOG.md and nuspec release notes.

2022-06-03 11:00 UTC, merged